Metrics
RaaLabs/Connectors.Lora pull request #15
Opened 2022-05-12 21:13 UTC by srudaa

## Summary

### Added

- Prometheus metrics server exposing Lora metadata 

### Changed

- Async Handlers

### Fixed

- Logging methods

2022-05-16 06:38 UTC, jonasmwahl requested changes
One comment on a prometheus metrics

2022-05-16 06:38 UTC, jonasmwahl commented on Source/Model/RxMetadata.cs
> +        /// Define application id
Define 'Gateway id', not 'application id'

2022-05-16 06:38 UTC, jonasmwahl commented on Source/MetricsHandler.cs
> +        private static readonly Gauge FCnt = Metrics.CreateGauge("raaedge_connector_lora_fcnt", "Lora message frame counter", new GaugeConfiguration { LabelNames = new[] { "iothub", "edge_device", "a
Could this be a [Counter](https://prometheus.io/docs/concepts/metric_types/#counter)

2022-05-16 08:43 UTC, srudaa commented on Source/MetricsHandler.cs
> +        private static readonly Gauge FCnt = Metrics.CreateGauge("raaedge_connector_lora_fcnt", "Lora message frame counter", new GaugeConfiguration { LabelNames = new[] { "iothub", "edge_device", "a
No. It needs to be gauge since the frame counter is just another value that can increase or decrease.

2022-05-18 07:11 UTC, jonasmwahl approved these changes

2022-05-18 14:33 UTC, merged